#!/bin/sh
# ========= 切换 JDK 版本 =========
# 用法：
#   sudo sh switch-java.sh 8
#   sudo sh switch-java.sh 17
#   sudo sh switch-java.sh           # 交互选择已安装的版本

JDK_DST="/usr/local/java"
JAVA_PROFILE="/etc/profile.d/java.sh"

log()  { printf "%s %s\n" "[INFO]" "$*"; }
err()  { printf "%s %s\n" "[ERR ]" "$*" >&2; exit 1; }

need_root() {
  if [ "$(id -u)" -ne 0 ]; then
    err "请用 root 运行（需要修改 $JDK_DST 和 $JAVA_PROFILE）"
  fi
}

list_versions() {
  ls -1d "$JDK_DST"/jdk*/ 2>/dev/null | sed "s|$JDK_DST/||;s|/||" || true
}

write_profile() {
  jdk_dir="$1"
  log "写入环境变量到 $JAVA_PROFILE ..."
  {
    echo "# generated by switch-java.sh @ $(date)"
    echo "export JAVA_HOME=\"$JDK_DST/current\""
    echo "export PATH=\"\$JAVA_HOME/bin:\$PATH\""
    if [ -d "$JDK_DST/$jdk_dir/jre" ] && [ -f "$JDK_DST/$jdk_dir/lib/tools.jar" ]; then
      echo "export CLASSPATH=\"\$JAVA_HOME/jre/lib/ext:\$JAVA_HOME/lib/tools.jar:\$CLASSPATH\""
    fi
  } > "$JAVA_PROFILE"
  # 立即生效
  # shellcheck disable=SC1091
  . "$JAVA_PROFILE"
}

switch_java() {
  ver="$1"
  candidates=$(list_versions | grep "$ver" || true)
  count=$(echo "$candidates" | wc -l)

  if [ "$count" -eq 0 ]; then
    err "未找到包含 [$ver] 的 JDK 版本，请确认已安装在 $JDK_DST"
  elif [ "$count" -gt 1 ]; then
    err "找到多个匹配 [$ver] 的版本，请更具体（候选：$candidates）"
  fi

  jdk_dir="$candidates"
  log "切换到 $jdk_dir ..."
  ln -sfn "$JDK_DST/$jdk_dir" "$JDK_DST/current"

  write_profile "$jdk_dir"

  log "已切换到 $jdk_dir"
  java -version
}

main() {
  need_root
  if [ $# -ge 1 ]; then
    switch_java "$1"
  else
    versions=$(list_versions)
    [ -z "$versions" ] && err "未找到任何已安装的 JDK，请先运行 install-java.sh 安装"

    log "检测到以下 JDK 版本："
    i=0
    for v in $versions; do
      i=$((i+1))
      echo "  [$i] $v"
      eval "opt_$i=\"$v\""
    done
    printf "请输入要切换的序号: "
    read -r idx
    eval "sel=\${opt_$idx:-}"
    [ -z "$sel" ] && err "无效选择"
    switch_java "$sel"
  fi
}

main "$@"
